# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'add_department.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(394, 219)
        Form.setMinimumSize(QtCore.QSize(394, 219))
        Form.setMaximumSize(QtCore.QSize(394, 219))
        self.lineEdit_1 = QtWidgets.QLineEdit(Form)
        self.lineEdit_1.setGeometry(QtCore.QRect(50, 60, 151, 31))
        self.lineEdit_1.setObjectName("lineEdit_1")
        self.lineEdit_2 = QtWidgets.QLineEdit(Form)
        self.lineEdit_2.setGeometry(QtCore.QRect(200, 60, 151, 31))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.add_Button = QtWidgets.QPushButton(Form)
        self.add_Button.setGeometry(QtCore.QRect(50, 130, 151, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.add_Button.setFont(font)
        self.add_Button.setObjectName("add_Button")
        self.back_Button = QtWidgets.QPushButton(Form)
        self.back_Button.setGeometry(QtCore.QRect(200, 130, 151, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.back_Button.setFont(font)
        self.back_Button.setObjectName("back_Button")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(200, 20, 81, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "增加院系信息"))
        self.add_Button.setText(_translate("Form", "提交"))
        self.back_Button.setText(_translate("Form", "返回"))
        self.label.setText(_translate("Form", "院系编号"))
        self.label_2.setText(_translate("Form", "院系名称"))
