# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'change_class.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(594, 219)
        Form.setMinimumSize(QtCore.QSize(594, 219))
        Form.setMaximumSize(QtCore.QSize(594, 219))
        self.cid_lineEdit = QtWidgets.QLineEdit(Form)
        self.cid_lineEdit.setGeometry(QtCore.QRect(50, 60, 131, 31))
        self.cid_lineEdit.setObjectName("cid_lineEdit")
        self.cname_lineEdit = QtWidgets.QLineEdit(Form)
        self.cname_lineEdit.setGeometry(QtCore.QRect(180, 60, 131, 31))
        self.cname_lineEdit.setObjectName("cname_lineEdit")
        self.pname_lineEdit = QtWidgets.QLineEdit(Form)
        self.pname_lineEdit.setGeometry(QtCore.QRect(440, 60, 131, 31))
        self.pname_lineEdit.setObjectName("pname_lineEdit")
        self.commitButton = QtWidgets.QPushButton(Form)
        self.commitButton.setGeometry(QtCore.QRect(100, 130, 151, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.commitButton.setFont(font)
        self.commitButton.setObjectName("commitButton")
        self.rollbackButton = QtWidgets.QPushButton(Form)
        self.rollbackButton.setGeometry(QtCore.QRect(370, 130, 151, 41))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.rollbackButton.setFont(font)
        self.rollbackButton.setObjectName("rollbackButton")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(50, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(180, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(310, 20, 71, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(440, 20, 91, 21))
        font = QtGui.QFont()
        font.setFamily("楷体")
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.num_textBrowser = QtWidgets.QTextBrowser(Form)
        self.num_textBrowser.setGeometry(QtCore.QRect(310, 60, 131, 31))
        self.num_textBrowser.setObjectName("num_textBrowser")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "班级信息修改"))
        self.commitButton.setText(_translate("Form", "提交修改"))
        self.rollbackButton.setText(_translate("Form", "撤销修改"))
        self.label.setText(_translate("Form", "编号"))
        self.label_2.setText(_translate("Form", "名称"))
        self.label_3.setText(_translate("Form", "人数"))
        self.label_4.setText(_translate("Form", "所属专业"))
